# Generated by Django 4.1.5 on 2023-01-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_api', '0002_alter_resume_recruiter_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_url',
            field=models.FileField(upload_to=''),
        ),
    ]
